name: Docker image publish
on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Create jar file
        run: mvn clean install

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build e Push no Azure Container Registry
        run: |
          docker build . --file Dockerfile --tag oajojjj/pace:latest
          docker tag oajojjj/pace:latest oajojjj/pace:$(date +%s)
          docker push oajojjj/pace:latest
